### ISSUE TITLE
Login page wont load

### ISSUE THREAD

**Issue by danishnazir** [auth0-samples/auth0-nodejs-webapp-sample#11]
Hi there i am running the sample i have correctly installed node modules and also i have inserted the values in the env file now when ever i open localhost:3000/login then a progress ring is shown and the app does not go forward can anybody tell me that what i am missing?

**Comment by chenkie** [comment]
Which sample (subdirectory) are you trying out?

**Comment by danishnazir** [comment]
i am using sample #2 i.e custom login now whenever i enter my details and click on login button there is an error printed out on the console
![capture](https://cloud.githubusercontent.com/assets/8293178/22403442/18395588-e639-11e6-84c5-0e35bd174d92.JPG)

**Comment by yashbhutwala** [comment]
I am running into the same issue. @danishnazir How did you resolve it?

**Comment by aaguiarz** [comment]
You need to set the domain where you application is running in the 'Web Origins' setting in the Dashboard (e.g. http://localhost:3000)
