### ISSUE TITLE
Missing parameter on callback url

### ISSUE THREAD

**Issue by rafanog** [auth0-samples/auth0-nodejs-webapp-sample#29]
The state parameter is missing on the callback url. To reproduce:
-Select the login option or go to "/login" route.
-Type the credentials of the account(in case you've logged in before, select "not your account")
-Click login.

![image](https://user-images.githubusercontent.com/15782359/37421034-b2df326e-278e-11e8-8040-15efb4e49a7e.png)

If on the seccond step you select the account used to log in before, the state parameter is correctly returned.

**Comment by albertoperdomo** [comment]
This no longer applies. Code was rewritten recently.
