### ISSUE TITLE
After logout, browser back brings back to authenticated state

### ISSUE THREAD

**Issue by pszakacscxn** [auth0-samples/auth0-nodejs-webapp-sample#31]
### How to reproduce

- Run 01-Login app
- Click on 'Log In' for login to the app.
- Auth0 login page appears, login as you want.
- The app is redirected to /user, where I can see my avatar.
- Click on the Logout tab
- Unauthenticated page appears with Login tab and button
- Hit browsers back button

### Actual
- Authenticated page appears with my avatar! 

### Expected
- I should login to my avatar (authenticated page)

**Comment by albertoperdomo** [comment]
Not reproducible with the current implementation, which was re-written after this issue was submitted.
