### ISSUE TITLE
user_metadata example?

### ISSUE THREAD

**Issue by Kilian** [auth0-samples/auth0-nodejs-webapp-sample#43]
I'm using the hosted login page variant and I want to verify I can get the user_metadata. I added `user_metadata` to the scope in routes/auth.js but they're not showing on the user object. How can I get the user_metadata?

**Comment by mathiasconradt** [comment]
@Kilian See https://community.auth0.com/t/when-successful-login-id-token-has-not-the-user-metadata/12400/2
