### ISSUE TITLE
dotenv.load()?

### ISSUE THREAD

**Issue by v-pietro** [auth0-samples/auth0-nodejs-webapp-sample#51]
Maybe to configure dotenv, you should use `dotenv.config()`?
https://github.com/auth0-samples/auth0-nodejs-webapp-sample/blob/51bfb79252e707255aea1ee7b2231ba775c600c3/01-Login/app.js#L15

**Comment by Troy-Dev** [comment]
There is inconsistency, `dotenv.config()` is used in other places in this package.
https://github.com/auth0-samples/auth0-nodejs-webapp-sample/blob/ae99dc6c85fa938e8661c07220d733606bdd7635/01-Login/routes/auth.js#L9
`load` was [removed from dotenv for consistency purposes](https://github.com/motdotla/dotenv#config), in a later version.

**Comment by MathRobin** [comment]
Fixed here https://github.com/auth0-samples/auth0-nodejs-webapp-sample/pull/53/files
