### ISSUE TITLE
Audience

### ISSUE THREAD

**Issue by felipeleusin** [auth0-samples/auth0-nodejs-webapp-sample#52]
Hi,

We we're integrating a NodeJS app and we got stuck for a while because the token being returned by Auth0 wasn't a JWT (and we needed it to be one to call other APIs) and instead an opaque token.

This was only solved when we included in the login passport call (https://github.com/auth0-samples/auth0-nodejs-webapp-sample/blob/master/01-Login/routes/auth.js#L13) the audience of our API.

I believe this should be included in the documentation, but I'm not entirely sure where so I'm opening this ticket to bring this to attention.

**Comment by lbalmaceda** [comment]
Hi @felipeleusin. The samples used to include the "userinfo audience" which triggered that format change as well. But it was [removed](https://github.com/auth0-samples/auth0-nodejs-webapp-sample/commit/69e2be81b43472dad7f01308dff63b18b43e7d54#diff-7e879c3a89ed322d74dd2f85d61876dfL22) in favor of **verifying** the ID Token and reading the user data from its contents. 
The different access token formats is already [documented here](https://auth0.com/docs/tokens/reference/access-token/access-token-formats).

**Comment by felipeleusin** [comment]
Ok. Thanks. This was something that me and my team missed and we kind of got it right by luck. Might be worthy to add some documentation in the quickstart.
