### ISSUE TITLE
ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by dylankbuckley** [auth0-samples/auth0-nodejs-webapp-sample#9]
Hi there. I change the .env file to reflect my client data and when I try to login I get ERR_CONNECTION_REFUSED in my browser console.

What could be going wrong?

**Comment by chenkie** [comment]
Is there anything else in the message? Where is it that the connection is refused?

**Comment by albertoperdomo** [comment]
Sample has been rewritten, so issue must be no longer relevant.
