### ISSUE TITLE
README links not working

### ISSUE THREAD

**Issue by ThomasGl** [auth0-samples/auth0-nodejs-webapp-sample#91]
Simply as the title says, non of the links in the readme seem to work.

Could anyone update those? Thank You

**Comment by ThomasGl** [comment]
more specifically on the "Whats Auth0" section

**Comment by dmtomczyk** [comment]
@ThomasGl see https://github.com/auth0-samples/auth0-nodejs-webapp-sample/pull/92

Looks like they've migrated from using the docs subdomain to sub-directories instead which hadn't been reflected on the docs changes. 

I submitted the PR, but the links are predictable so if you keep running into that issue just pay attention to the formatting and you should be able to derive the new URL.

**Comment by frederikprijck** [comment]
Thanks for raising, this has been resolved https://github.com/auth0-samples/auth0-nodejs-webapp-sample/pull/92

Again, thanks for the PR @dmtomczyk
